package Labs;
/*
Title: Even Fibonacci Numbers
Problem 2
Question: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
The page has been left unattended for too long and that link/button is no longer active. Please refresh the page.
 */
public class EvenFibonacciNumbers {
    public static void main(String[] args) {
        printEvenFibonacci();
    }

    public static int evenFibonacci(int num){
        int sum = 0;
        int starting = 1;
        int secondNum = 2;
        while(secondNum <= num){
            if(secondNum % 2 == 0){
                sum += secondNum;
            }
        }
        return sum;
    }

    public static void printEvenFibonacci(){
        System.out.println(evenFibonacci(4000000));
    }
}
